binding_config:
vast_config:
  addr: "0.0.0.0:11111"

  s2s_list:
    - "./config/s2s.xml"
  pmp_list:
    - "./config/pmp.xml"

control_config:
  s2s_control:
    succ_rate: 0.8
    avg_cost: 100 #毫秒级别
    diff_cost: 200
  adx_control:
    succ_rate: 0.6
    avg_cost: 50
    diff_cost: 30
