binding_config:
  addr: "0.0.0.0:11111"

vast_config:
  video_list:
    - "../config/s2s.xml"
  no_video_list:
    - "../config/pmp.xml"

control_config:
  s2s_control:
    succ_rate: 0.8
    avg_cost: 100 #毫秒级别
  adx_control:
    succ_rate: 0.6
    avg_cost: 150
